name : Bump version

permissions: 
    contents: write

on: 
  pull_request:
    types : [closed]
    branches: [main]

jobs:

  release: 
    if : github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with:
          persist-credentials: true
    
    - name: Bump Version
      id: bump
      run : |
        version=$(cat version.txt)
        new_version=$((version + 1))
        echo $new_version > version.txt
        git config user.name "github bot"
        git config user.email "github-actions@users.noreply.github.com"
        git add version.txt
        git commit -m "chore: bump version to v$new_version"
        git push origin HEAD:main
        echo "::set-output name=new_version::$new_version"

    
    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          tag_name: v${{ steps.bump.outputs.new_version }}
          release_name: "v${{ steps.bump.outputs.new_version }}"
          body: "Automated release of version v${{ steps.bump.outputs.new_version }}"

    - name: Upload version file
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: version.txt
        asset_name: version.txt
        asset_content_type: text/plain
    
